<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_09";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'miguel123', 'Miguel Robledo')",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'victor123', 'Victor Fosch')",

                
                "INSERT INTO " + schema + ".SHOP VALUES (NEXT VALUE FOR SHOP_GEN, 'Amposta', '5', '43870'," +
                    " 'Influx', 'C/Barcelona')",
                "INSERT INTO " + schema + ".SHOP VALUES (NEXT VALUE FOR SHOP_GEN, 'Barcelona', '8', '08001'," +
                    " 'Sunrise Mart', 'C/Granada')",
                "INSERT INTO " + schema + ".SHOP VALUES (NEXT VALUE FOR SHOP_GEN, 'Madrid', '15', '28002'," +
                    " 'Moonlight Goods', 'Avda/Valencia')",
                "INSERT INTO " + schema + ".SHOP VALUES (NEXT VALUE FOR SHOP_GEN, 'Valencia', '20', '46003'," +
                    " 'Starry Shop', 'C/Sevilla')",
                
                "INSERT INTO " + schema + ".GAME VALUES (NEXT VALUE FOR GAME_GEN, 1, 'Joc de plataformes Super Mario per a la gameboy.', 'GAME_BOY', 'Super Mario', 7.5, 'PLATAFORM')",
                "INSERT INTO " + schema + ".GAME VALUES (NEXT VALUE FOR GAME_GEN, 1, 'Joc de velocitat y plataformes amb Sonic.', 'MEGA_DRIVE', 'Sonic the Hedgehog', 9.99, 'PLATAFORM')",
                "INSERT INTO " + schema + ".GAME VALUES (NEXT VALUE FOR GAME_GEN, 1, 'El clàssic joc d''arcade amb l''icònic Pac-Man.', 'ATARI_2600', 'Pac-Man', 6.50, 'ACTION')",
                "INSERT INTO " + schema + ".GAME VALUES (NEXT VALUE FOR GAME_GEN, 1, 'Joc de lluita clàssic amb personatges icònics.', 'MEGA_DRIVE', 'Street Fighter II', 12.00, 'FIGHT')",
                "INSERT INTO " + schema + ".GAME VALUES (NEXT VALUE FOR GAME_GEN, 1, 'Aventura èpica al món de Hyrule.', 'NINTENDO_64', 'The Legend of Zelda', 14.20, 'RPG')",
                   
                "INSERT INTO " + schema + ".GAMES_SHOP VALUES (1, 1)  -- Super Mario en Influx",
                "INSERT INTO " + schema + ".GAMES_SHOP VALUES (2, 2)  -- Sonic en Sunrise Mart",
                "INSERT INTO " + schema + ".GAMES_SHOP VALUES (3, 3)  -- Pac-Man en Moonlight Goods",
                "INSERT INTO " + schema + ".GAMES_SHOP VALUES (4, 4)  -- Street Fighter II en Starry Shop",
                "INSERT INTO " + schema + ".GAMES_SHOP VALUES (5, 1)  -- The Legend of Zelda en Influx",
                "INSERT INTO " + schema + ".GAMES_SHOP VALUES (4, 2)  -- Street Fighter II en Sunrise Mart",
                "INSERT INTO " + schema + ".GAMES_SHOP VALUES (5, 3)  -- The Legend of Zelda en Moonlight Goods",
                
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'sob', 'sob')",
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'victor123', 'Victor Fosch')",
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'miguel123', 'Miguel Robledo')"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
